### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by qzcad** [qzcad/pyfem#1]
- [x] Add Gauss-Legendre rules (tetrahedra and hexahedra)
- [x] Add Gauss–Lobatto rules (interval, quad, hexahedra)
- [x] 2D isoparametric shape functions
- [x] Function for plane stress/strain matrices generation
- [x] Function for the FEM plane stress-strain analysis
- [x] Plate's stress-strain state analysis
- [ ] Plate's buckling analysis
- [x] Shell's stress-strain state analysis
- [ ] Shell's buckling analysis
